In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [68]:
data=pd.read_csv('Corona_NLP_train.csv',encoding='latin-1')
data

UserName  ScreenName                      Location     TweetAt  \
0          3799       48751                        London  16-03-2020   
1          3800       48752                            UK  16-03-2020   
2          3801       48753                     Vagabonds  16-03-2020   
3          3802       48754                           NaN  16-03-2020   
4          3803       48755                           NaN  16-03-2020   
...         ...         ...                           ...         ...   
41152     44951       89903  Wellington City, New Zealand  14-04-2020   
41153     44952       89904                           NaN  14-04-2020   
41154     44953       89905                           NaN  14-04-2020   
41155     44954       89906                           NaN  14-04-2020   
41156     44955       89907  i love you so much || he/him  14-04-2020   

                                           OriginalTweet           Sentiment  
0      @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...             Neutral  
1      advice Talk to your neighbours family to excha...            Positive  
2      Coronavirus Australia: Woolworths to give elde...            Positive  
3      My food stock is not the only one which is emp...            Positive  
4      Me, ready to go at supermarket during the #COV...  Extremely Negative  
...                                                  ...                 ...  
41152  Airline pilots offering to stock supermarket s...             Neutral  
41153  Response to complaint not provided citing COVI...  Extremely Negative  
41154  You know it’s getting tough when @KameronWild...            Positive  
41155  Is it wrong that the smell of hand sanitizer i...             Neutral  
41156  @TartiiCat Well new/used Rift S are going for ...            Negative  

[41157 rows x 6 columns]

In [69]:
data.isna().sum()

UserName            0
ScreenName          0
Location         8590
TweetAt             0
OriginalTweet       0
Sentiment           0
dtype: int64

In [70]:
data['Location'].unique()

array(['London', 'UK', 'Vagabonds', ..., 'Juba south sudan', 'OHIO',
       'i love you so much || he/him'], dtype=object)

In [71]:
X_train=data[['OriginalTweet']]
y_train=data[['Sentiment']]
X_train=X_train.iloc[:10000,:]
y_train=y_train.iloc[:10000,:]
X_train

OriginalTweet
0     @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...
1     advice Talk to your neighbours family to excha...
2     Coronavirus Australia: Woolworths to give elde...
3     My food stock is not the only one which is emp...
4     Me, ready to go at supermarket during the #COV...
...                                                 ...
9995  Popped out for food in #oldham \r\r\nPolite , ...
9996  Found my first paper towel in weeks at a super...
9997  Through the #Coronavirus chaos, I’m grateful ...
9998  Therapist, Lisa Olivera gave gratitude cards t...
9999  Older people and those with other conditions, ...

[10000 rows x 1 columns]

In [72]:
y_train

Sentiment
0                Neutral
1               Positive
2               Positive
3               Positive
4     Extremely Negative
...                  ...
9995            Positive
9996            Positive
9997            Negative
9998            Positive
9999  Extremely Negative

[10000 rows x 1 columns]

In [73]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
Lemmatizer=WordNetLemmatizer()

In [74]:
#so X contains all sentences now which can be handled with tfidf vectorizer to convert into dense vectors basically X contain list of sentences
def process_sentence(sentence):
    words=sentence.split()
    words=[Lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    temp=" ".join(words)
    return temp

In [75]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [76]:
tfidf=TfidfVectorizer(max_features=1000,ngram_range=(1,2)) #will consider the top 5000 features from all the sentences int he particular column
X_train_vectorized=tfidf.fit_transform(X_train['OriginalTweet']).toarray()
print(X_train_vectorized.shape)

(10000, 1000)


In [77]:
X_train_vectorized

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.22510787, 0.        ,
        0.        ]])

In [78]:
X_train=X_train_vectorized
X_train

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.22510787, 0.        ,
        0.        ]])

In [79]:
print(X_train.shape)

(10000, 1000)


In [80]:
import pickle
with open('tfidf.pkl','wb') as file:
    pickle.dump(tfidf,file)


In [81]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from xgboost import XGBClassifier

In [82]:
def prediction_model(model):
    model=model()
    model.fit(X_train,y_train)
    y_pred=model.predict(X_train)
    print(f"The accuracy score on training data by the {model} is {accuracy_score(y_train,y_pred)}")
    print(confusion_matrix(y_train,y_pred))
    print(classification_report(y_train,y_pred))
    

In [83]:
prediction_model(RandomForestClassifier)

c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv2\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


The accuracy score on training data by the RandomForestClassifier() is 0.9998
[[1571    0    0    0    0]
 [   0 1461    0    0    1]
 [   0    0 2527    0    0]
 [   0    0    0 1768    1]
 [   0    0    0    0 2671]]
                    precision    recall  f1-score   support

Extremely Negative       1.00      1.00      1.00      1571
Extremely Positive       1.00      1.00      1.00      1462
          Negative       1.00      1.00      1.00      2527
           Neutral       1.00      1.00      1.00      1769
          Positive       1.00      1.00      1.00      2671

          accuracy                           1.00     10000
         macro avg       1.00      1.00      1.00     10000
      weighted avg       1.00      1.00      1.00     10000



In [84]:
forest=RandomForestClassifier()
forest.fit(X_train,y_train)
with open('randomforest.pkl','wb') as file:
    pickle.dump(forest,file)

c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv2\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [85]:
y_train['Sentiment']=y_train['Sentiment'].map({'Extremely Negative':"Negative","Extremely Positive":"Positive","Negative":"Negative","Positive":"Positive","Neutral":"Neutral"})
y_train

Sentiment
0      Neutral
1     Positive
2     Positive
3     Positive
4     Negative
...        ...
9995  Positive
9996  Positive
9997  Negative
9998  Positive
9999  Negative

[10000 rows x 1 columns]

In [86]:
y_train['Sentiment'].value_counts()

Sentiment
Positive    4133
Negative    4098
Neutral     1769
Name: count, dtype: int64

In [98]:
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
#So we have to convert the y_train to categorical data but before that we need to ensure that each categorical class of y train must be a number
y_train=to_categorical(y_train,num_classes=3)
y_train

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [99]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN,Dense,Embedding
from tensorflow.keras.callbacks import EarlyStopping

In [100]:
model=Sequential()
model

<Sequential name=sequential_3, built=False>

In [101]:
print(X_train.shape)

(10000, 1000)


In [102]:
#The syntax of model.add(Embedding(input_dim(which is the voc size),output_dim=,max_len=maxlen among all input vectors must be same for simple RNN,LSTMRNN))
model.add(Embedding(X_train.shape[1],output_dim=128,input_length=X_train.shape[1]))
#First added the embedding layer

c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv2\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [103]:
model.add(SimpleRNN(64,activation='relu'))
model.add(Dense(3,activation='sigmoid'))
#hidden layer will be simpleRNN will be of 64 neurons with activation fucntion relu and then output layer with Dense layer with 3 neurons and activation will be sigmoid for multiclass classification and loss will be categorical_crossentropy

In [104]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [105]:
with open('encoder.pkl','wb') as file:
    pickle.dump(encoder,file)

In [106]:
earlystopping=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [107]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history=model.fit(
    X_train,y_train,
    validation_split=0.2,
    epochs=100,
    callbacks=[earlystopping]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 48s 187ms/step - accuracy: 0.4084 - loss: 1.0512 - val_accuracy: 0.3950 - val_loss: 1.0454
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 40s 158ms/step - accuracy: 0.4120 - loss: 1.0396 - val_accuracy: 0.3950 - val_loss: 1.0387
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 41s 162ms/step - accuracy: 0.4077 - loss: 1.0387 - val_accuracy: 0.3950 - val_loss: 1.0393
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 50s 201ms/step - accuracy: 0.4099 - loss: 1.0397 - val_accuracy: 0.3950 - val_loss: 1.0387
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 40s 158ms/step - accuracy: 0.4188 - loss: 1.0383 - val_accuracy: 0.3950 - val_loss: 1.0375
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 40s 159ms/step - accuracy: 0.4111 - loss: 1.0402 - val_accuracy: 0.3950 - val_loss: 1.0363
Epoch 7/100
240/250 ━━━━━━━━━━━━━━━━━━━━ 1s 154ms/step - accuracy: 0.4195 - loss: 1.0334

KeyboardInterrupt: 