In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [41]:
data=pd.read_csv('Corona_NLP_train.csv',encoding='latin-1')
data

UserName  ScreenName                      Location     TweetAt  \
0          3799       48751                        London  16-03-2020   
1          3800       48752                            UK  16-03-2020   
2          3801       48753                     Vagabonds  16-03-2020   
3          3802       48754                           NaN  16-03-2020   
4          3803       48755                           NaN  16-03-2020   
...         ...         ...                           ...         ...   
41152     44951       89903  Wellington City, New Zealand  14-04-2020   
41153     44952       89904                           NaN  14-04-2020   
41154     44953       89905                           NaN  14-04-2020   
41155     44954       89906                           NaN  14-04-2020   
41156     44955       89907  i love you so much || he/him  14-04-2020   

                                           OriginalTweet           Sentiment  
0      @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...             Neutral  
1      advice Talk to your neighbours family to excha...            Positive  
2      Coronavirus Australia: Woolworths to give elde...            Positive  
3      My food stock is not the only one which is emp...            Positive  
4      Me, ready to go at supermarket during the #COV...  Extremely Negative  
...                                                  ...                 ...  
41152  Airline pilots offering to stock supermarket s...             Neutral  
41153  Response to complaint not provided citing COVI...  Extremely Negative  
41154  You know it’s getting tough when @KameronWild...            Positive  
41155  Is it wrong that the smell of hand sanitizer i...             Neutral  
41156  @TartiiCat Well new/used Rift S are going for ...            Negative  

[41157 rows x 6 columns]

In [42]:
data.isna().sum()

UserName            0
ScreenName          0
Location         8590
TweetAt             0
OriginalTweet       0
Sentiment           0
dtype: int64

In [43]:
data['Location'].unique()

array(['London', 'UK', 'Vagabonds', ..., 'Juba south sudan', 'OHIO',
       'i love you so much || he/him'], dtype=object)

In [44]:
X_train=data[['OriginalTweet']]
y_train=data[['Sentiment']]
X_train=X_train.iloc[:10000,:]
y_train=y_train.iloc[:10000,:]
X_train

OriginalTweet
0     @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...
1     advice Talk to your neighbours family to excha...
2     Coronavirus Australia: Woolworths to give elde...
3     My food stock is not the only one which is emp...
4     Me, ready to go at supermarket during the #COV...
...                                                 ...
9995  Popped out for food in #oldham \r\r\nPolite , ...
9996  Found my first paper towel in weeks at a super...
9997  Through the #Coronavirus chaos, I’m grateful ...
9998  Therapist, Lisa Olivera gave gratitude cards t...
9999  Older people and those with other conditions, ...

[10000 rows x 1 columns]

In [45]:
y_train

Sentiment
0                Neutral
1               Positive
2               Positive
3               Positive
4     Extremely Negative
...                  ...
9995            Positive
9996            Positive
9997            Negative
9998            Positive
9999  Extremely Negative

[10000 rows x 1 columns]

In [46]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
Lemmatizer=WordNetLemmatizer()

In [47]:
#so X contains all sentences now which can be handled with tfidf vectorizer to convert into dense vectors basically X contain list of sentences
def process_sentence(sentence):
    words=sentence.split()
    words=[Lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    temp=" ".join(words)
    return temp

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [49]:
tfidf=TfidfVectorizer(max_features=1000,ngram_range=(1,2)) #will consider the top 5000 features from all the sentences int he particular column
X_train_vectorized=tfidf.fit_transform(X_train['OriginalTweet']).toarray()
print(X_train_vectorized.shape)

(10000, 1000)


In [50]:
X_train_vectorized

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.22510787, 0.        ,
        0.        ]])

In [51]:
X_train=X_train_vectorized
X_train

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.22510787, 0.        ,
        0.        ]])

In [52]:
print(X_train.shape)

(10000, 1000)


In [53]:
import pickle
with open('tfidf.pkl','wb') as file:
    pickle.dump(tfidf,file)


In [54]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from xgboost import XGBClassifier

In [55]:
def prediction_model(model):
    model=model()
    model.fit(X_train,y_train)
    y_pred=model.predict(X_train)
    print(f"The accuracy score on training data by the {model} is {accuracy_score(y_train,y_pred)}")
    print(confusion_matrix(y_train,y_pred))
    print(classification_report(y_train,y_pred))
    

In [56]:
prediction_model(RandomForestClassifier)

c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv2\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


The accuracy score on training data by the RandomForestClassifier() is 0.9998
[[1571    0    0    0    0]
 [   0 1461    0    0    1]
 [   0    0 2527    0    0]
 [   0    0    0 1769    0]
 [   0    0    0    1 2670]]
                    precision    recall  f1-score   support

Extremely Negative       1.00      1.00      1.00      1571
Extremely Positive       1.00      1.00      1.00      1462
          Negative       1.00      1.00      1.00      2527
           Neutral       1.00      1.00      1.00      1769
          Positive       1.00      1.00      1.00      2671

          accuracy                           1.00     10000
         macro avg       1.00      1.00      1.00     10000
      weighted avg       1.00      1.00      1.00     10000



c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv2\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


KeyboardInterrupt: 